import PDFDocument from "pdfkit";

export const generatePdf = async (data) => {
    return new Promise((resolve, reject) => {

        const doc = new PDFDocument({
            size: "A4",
            margin: 50,
            bufferPages: true,
            info: {
                Author: "Orchestrix",
                Title: data.title || "Untitled",
                Creator: "Orchestrix"
            }
        });

        const chunks = [];

        doc.on("data", chunk => chunks.push(chunk));
        doc.on("end", () => resolve(Buffer.concat(chunks)));
        doc.on("error", reject);

        const pageWidth =
            doc.page.width -
            doc.page.margins.left -
            doc.page.margins.right;

        // ==========================
        // Title
        // ==========================

        doc
            .fillColor("#2563EB")
            .font("Helvetica-Bold")
            .fontSize(28)
            .text(data.title || "Untitled", {
                align: "center"
            });

        if (data.subtitle) {

            doc.moveDown(0.5);

            doc
                .fillColor("#6B7280")
                .font("Helvetica")
                .fontSize(13)
                .text(data.subtitle, {
                    align: "center"
                });

        }

        doc.moveDown(1.5);

        // ==========================
        // Sections
        // ==========================

        (data.sections || []).forEach(section => {

            // New page if required
            if (doc.y > 680) {
                doc.addPage();
            }

            const headerY = doc.y;

            // Header background
            doc
                .roundedRect(
                    doc.page.margins.left,
                    headerY,
                    pageWidth,
                    30,
                    8
                )
                .fill("#EEF2FF");

            // Header text
            doc
                .fillColor("#1D4ED8")
                .font("Helvetica-Bold")
                .fontSize(17)
                .text(
                    section.heading || "",
                    doc.page.margins.left + 12,
                    headerY + 8
                );

            doc.moveDown(2);

            // Bullet points
            (section.points || []).forEach(point => {

                if (doc.y > 720) {
                    doc.addPage();
                }

                const startY = doc.y;

                // Blue bullet
                doc
                    .fillColor("#2563EB")
                    .circle(
                        doc.page.margins.left + 4,
                        startY + 6,
                        2.5
                    )
                    .fill();

                // Bullet text
                doc
                    .fillColor("#374151")
                    .font("Helvetica")
                    .fontSize(11)
                    .text(
                        point,
                        doc.page.margins.left + 15,
                        startY,
                        {
                            width: pageWidth - 15,
                            lineGap: 5,
                            align: "justify"
                        }
                    );

                doc.moveDown(0.8);

            });

            // Separator line
            doc
                .strokeColor("#E5E7EB")
                .lineWidth(1)
                .moveTo(
                    doc.page.margins.left,
                    doc.y
                )
                .lineTo(
                    doc.page.width - doc.page.margins.right,
                    doc.y
                )
                .stroke();

            doc.moveDown();

        });

        // ==========================
        // Footer
        // ==========================

        const range = doc.bufferedPageRange();

        for (
            let i = range.start;
            i < range.start + range.count;
            i++
        ) {

            doc.switchToPage(i);

            doc
                .fillColor("#9CA3AF")
                .font("Helvetica")
                .fontSize(9);

            doc.text(
                "Generated by Orchestrix",
                50,
                doc.page.height - 35
            );

            doc.text(
                `Page ${i - range.start + 1} of ${range.count}`,
                0,
                doc.page.height - 35,
                {
                    align: "right"
                }
            );
        }

        doc.end();

    });
};