import pptxgen from "pptxgenjs";

const COLORS = {
    primary: "2563EB",
    secondary: "0F172A",
    text: "334155",
    light: "F8FAFC",
    border: "E2E8F0",
    white: "FFFFFF",
    muted: "64748B",
};

export const generatePpt = async (data) => {
    const ppt = new pptxgen();

    ppt.layout = "LAYOUT_WIDE";
    ppt.author = "Orchestrix";
    ppt.company = "Orchestrix";
    ppt.subject = data.title;
    ppt.title = data.title;

    ppt.theme = {
        headFontFace: "Aptos",
        bodyFontFace: "Aptos",
        lang: "en-US"
    };

    addCover(ppt, data);

    data?.slides?.forEach((slideData, index) => {
        addContentSlide(
            ppt,
            slideData.title,
            slideData.points,
            index + 1,
            data.slides.length
        );
    });

    addThankYou(ppt);

    return ppt;
};

function addCover(ppt, data) {
    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.primary
    };

    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.18,
        fill: {
            color: "60A5FA"
        },
        line: {
            color: "60A5FA"
        }
    });

    slide.addText(data.title, {
        x: 0.7,
        y: 1.5,
        w: 12,
        h: 0.8,
        align: "center",
        bold: true,
        fontSize: 28,
        color: COLORS.white
    });

    slide.addText(data.subtitle || "", {
        x: 1,
        y: 2.5,
        w: 11.5,
        h: 0.5,
        align: "center",
        fontSize: 16,
        color: "DBEAFE"
    });

    slide.addShape(ppt.ShapeType.line, {
        x: 3,
        y: 3.3,
        w: 7.3,
        h: 0,
        line: {
            color: "93C5FD",
            width: 1.5
        }
    });

    slide.addText("Generated by Orchestrix", {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.3,
        align: "center",
        fontSize: 11,
        color: "BFDBFE"
    });
}

function addContentSlide(ppt, title, points, page, total) {

    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.white
    };

    slide.addText(title, {
        x: 0.6,
        y: 0.35,
        w: 10,
        h: 0.4,
        bold: true,
        fontSize: 24,
        color: COLORS.primary
    });

    slide.addShape(ppt.ShapeType.line, {
        x: 0.6,
        y: 0.82,
        w: 12,
        h: 0,
        line: {
            color: COLORS.border,
            width: 1.2
        }
    });

    const visiblePoints = (points || []).slice(0, 6);

    visiblePoints.forEach((point, index) => {

        const y = 1.2 + index * 0.78;

        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.7,
            y,
            w: 12,
            h: 0.58,
            rectRadius: 0.08,
            fill: {
                color: index % 2 === 0 ? "EFF6FF" : "F8FAFC"
            },
            line: {
                color: COLORS.border
            }
        });

        slide.addShape(ppt.ShapeType.ellipse, {
            x: 0.92,
            y: y + 0.22,
            w: 0.12,
            h: 0.12,
            fill: {
                color: COLORS.primary
            },
            line: {
                color: COLORS.primary
            }
        });

        slide.addText(point, {
            x: 1.2,
            y: y + 0.08,
            w: 11,
            h: 0.35,
            fontSize: 15,
            color: COLORS.text,
            fit: "shrink"
        });

    });

    // Footer

    slide.addShape(ppt.ShapeType.line, {
        x: 0.6,
        y: 6.7,
        w: 12,
        h: 0,
        line: {
            color: COLORS.border,
            width: 1
        }
    });

    slide.addText("Orchestrix", {
        x: 0.6,
        y: 6.82,
        w: 2,
        h: 0.2,
        fontSize: 10,
        color: COLORS.muted
    });

    slide.addText(`${page}/${total}`, {
        x: 11.8,
        y: 6.82,
        w: 1,
        h: 0.2,
        align: "right",
        fontSize: 10,
        color: COLORS.muted
    });

}

function addThankYou(ppt) {

    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.secondary
    };

    slide.addText("Thank You", {
        x: 0,
        y: 2.2,
        w: 13.33,
        h: 0.8,
        align: "center",
        bold: true,
        fontSize: 34,
        color: COLORS.white
    });

    slide.addText("Questions?", {
        x: 0,
        y: 3.2,
        w: 13.33,
        h: 0.4,
        align: "center",
        fontSize: 18,
        color: "CBD5E1"
    });

    slide.addShape(ppt.ShapeType.line, {
        x: 4,
        y: 4,
        w: 5.3,
        h: 0,
        line: {
            color: "334155",
            width: 1
        }
    });

    slide.addText("Generated by Orchestrix", {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        fontSize: 10,
        color: "94A3B8"
    });

}